feat: :sparkles: Add ft_strchr_i()
minishell-jiphyeonjeon/Rank03-Minishell pull request #29
Opened 2022-02-10 16:06 UTC by Hyoj-Kim

문자열 속 특정 문자의 위치를 찾는 함수

#28

2022-02-10 16:11 UTC, Hyoj-Kim commented
header 파일 수정하면서 equal 함수 오타와 split 함수 프로토타입 누락된 부분까지 함께 추가했습니다!

2022-02-10 22:17 UTC, scarf005 requested changes
굳굳굳 인자가 `char c`이면 조금 더 직관적일 것 같아요

2022-02-11 01:12 UTC, Hyoj-Kim commented
아 저도 그부분이 고민이었어요!! 수정완료했습니다ㅏ

2022-02-11 01:33 UTC, scarf005 approved these changes
LGTM!

2022-02-11 02:10 UTC, merged