Run ast
minishell-jiphyeonjeon/Rank03-Minishell pull request #74
Opened 2022-02-22 15:34 UTC by scarf005

### 개요
![image](https://user-images.githubusercontent.com/54838975/155165507-1eda9bb5-0475-4813-a37d-76115097fbd7.png)

2022-02-22 16:04 UTC, scarf005 commented on include/minishell_type.h
> +
헤더 순서 오류 해결하기 위해 이동

2022-02-22 16:06 UTC, scarf005 commented on src/api/path.c
> +	del_arr(raw);
메모리 누수!

2022-02-22 16:07 UTC, scarf005 commented on src/exec/exec.c
> +	envp = new_env_to_envp(shell->env);
TODO: 리다이렉션 && 파이프 기능 추가

2022-02-22 17:05 UTC, Hyoj-Kim commented
파일 35개 실화인가요................ :open_mouth:

2022-02-22 17:20 UTC, Hyoj-Kim commented on include/ast_type.h
> +typedef struct s_AST_SCRIPTS
생각해보니까 SCRIPT는 무조건 하나라서 S가 없어도 될 것 같네요..ㅎ

2022-02-22 17:47 UTC, Hyoj-Kim requested changes
만들어진 parser 기반으로 prompt 쪽 전면 수정하시느라 정말 고생많으셨습니다!
pipeline을 script로 바꾸는 작업까지 한 번에 하시면서 commit과 변경파일이 너무 많아졌는데, 그러다보니 변환작업이 완성되지는 않은 것 같습니다.
이 PR에서 다 고치고 넘어갈지 아니면 parser쪽은 제가 다시 수정할지 오전에 회의하고 진행하시죠.

2022-02-22 17:47 UTC, Hyoj-Kim commented on include/parser.h
> +void			del_ast_pipeline(t_AST_SCRIPTS *pipeline);
PIPELINE이 SCRIPT의 개념과 혼동된다는 것 때문에 타입 이름을 변경했으니, 관련 함수 이름이나 변수도 전부 바꿔줘야한다고 생각합니다.
번거로우실거라고 말씀드렸던 이유도 이 점 때문이었어요.

2022-02-22 17:47 UTC, Hyoj-Kim commented on include/parser.h
> +void			del_ast_pipeline(t_AST_SCRIPTS *pipeline);
추후 $?를 추가할 때 있어서 제가 혼란스러울 것 같아서 전부 통일성있게 고쳐주시길 부탁드려요 :pray: 

쭉 확인해보니까 is_ast_pipeline() 함수에서 true가 나와서 그 이후에 실행하는 함수는 pipeline이 들어가도 되지만, 그런게 아니라면 모두 script로 바꿔야한다고 봅니다.

2022-02-22 17:47 UTC, Hyoj-Kim commented on include/tree.h
> +void	ast_script_repr(t_AST_SCRIPTS *pipeline);
아 이런경우라면 위에서 pipeline을 사용하는거 인정.
하지만 밑의 경우는 변수 이름도 script로 하는게 명확하지 않을까요?

2022-02-22 17:47 UTC, Hyoj-Kim commented on src/parser/parser.c
> +	t_AST_SCRIPTS	*pipeline;
여기도 변수명 pipeline이 아니라 script로 수정이 필요합니다.

2022-02-22 17:47 UTC, Hyoj-Kim commented on include/parser.h
> +bool			is_ast_command(t_AST_SCRIPTS *pipeline);
이 함수들을 사용한 이후에 변수명이 pipeline으로 되는건 문제없지만,
일단 이 함수들에 넣어줄 인자는 script가 되어야한다고 생각합니다.

2022-02-23 02:36 UTC, scarf005 commented on include/parser.h
> +void			del_ast_pipeline(t_AST_SCRIPTS *pipeline);
수정 완료!

2022-02-23 03:09 UTC, Hyoj-Kim approved these changes
라이브쉐어 덕분에 변수이름 수정하는 것도 실시간으로 리뷰할 수 있어서 너무 좋네요!!
1시간 가량 설명해주시고 페어프로그래밍 하시느라 고생많으셨습니다~~
탄력받은 만큼 이번주도 화이팅 :rocket:

2022-02-23 03:40 UTC, merged